const state={section:'overview',ticketFilter:{status:'all',priority:'all'},customerSearch:'',kbSearch:''};
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function initials(name){return name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function tag(text,cls){return `<span class="tag ${cls}">${esc(text)}</span>`}
function renderOverview(){
 $('#volume-chart').innerHTML=volume.map(v=>`<div class="bar" style="height:${(v/70)*100}%"><span class="bar-label">${v}</span></div>`).join('');
 const max=Math.max(...intents.map(x=>x[1])); $('#intent-list').innerHTML=intents.map(([label,val])=>`<div class="metric-row"><span class="label">${label}</span><span class="value">${val}%</span><div class="meter"><span style="width:${(val/max)*100}%"></span></div></div>`).join('');
 $('#priority-table').innerHTML=tableHtml(ticketData.slice(0,5),true); $('#agent-capacity').innerHTML=agents.map(a=>`<div class="agent-item"><div class="agent-avatar">${a[0]}</div><div class="agent-meta"><strong>${a[1]}</strong><small>${a[2]}</small></div><div class="capacity">${a[3]}%</div></div>`).join('');
}
function tableHtml(rows,compact=false){return `<table class="table"><thead><tr><th>Ticket</th><th>Customer</th><th>Intent</th><th>Priority</th><th>Status</th><th>SLA</th><th>Owner</th></tr></thead><tbody>${rows.map(t=>`<tr data-ticket="${t.id}" class="clickable"><td><span class="ticket-id">${t.id}</span><div class="subtle">${t.channel}</div></td><td><span class="customer-name">${t.customer}</span><div class="subtle">${t.account}</div></td><td>${t.intent}</td><td>${tag(t.priority,t.priority)}</td><td>${tag(t.status,t.status)}</td><td><strong>${t.sla}</strong></td><td>${t.agent}</td></tr>`).join('')}</tbody></table>`}
function renderTickets(){let rows=ticketData.filter(t=>(state.ticketFilter.status==='all'||t.status===state.ticketFilter.status)&&(state.ticketFilter.priority==='all'||t.priority===state.ticketFilter.priority)); const q=$('#global-search').value.trim().toLowerCase();if(q) rows=rows.filter(t=>Object.values(t).join(' ').toLowerCase().includes(q));$('#ticket-count').textContent=rows.length;$('#tickets-table').innerHTML=tableHtml(rows);bindTicketRows();}
function renderCustomers(){const q=state.customerSearch.toLowerCase();const rows=customers.filter(c=>!q||(c.name+' '+c.id).toLowerCase().includes(q));$('#customer-grid').innerHTML=rows.map(c=>`<article class="customer-card"><div class="customer-head"><div class="customer-avatar">${initials(c.name)}</div><div><h3>${c.name}</h3><p>${c.id} · ${c.tier} customer</p></div></div><div class="customer-stats"><div class="mini-stat"><span>Tickets</span><strong>${c.tickets}</strong></div><div class="mini-stat"><span>CSAT</span><strong>${c.csat}</strong></div><div class="mini-stat"><span>Lifetime value</span><strong>${c.lifetime}</strong></div><div class="mini-stat"><span>Support trend</span><strong>${c.tickets>4?'Watch':'Stable'}</strong></div></div>${c.risk?`<div class="risk">${esc(c.risk)}</div>`:''}</article>`).join('');}
function renderSLA(){const rows=ticketData.filter(t=>t.status!=='resolved').sort((a,b)=>parseSla(a.sla)-parseSla(b.sla));$('#sla-table').innerHTML=tableHtml(rows);bindTicketRows();}
function parseSla(s){if(s==='—') return 9999; const m=s.match(/(?:(\d+)h\s*)?(?:(\d+)m)?/);return (Number(m?.[1]||0)*60)+Number(m?.[2]||0)}
function renderKB(){const q=state.kbSearch.toLowerCase();const rows=kb.filter(k=>!q||(k.title+' '+k.category+' '+k.body+' '+k.content.map(x=>x.join(' ')).join(' ')).toLowerCase().includes(q));$('#kb-grid').innerHTML=rows.map(k=>`<article class="kb-card clickable-kb" data-kb="${k.id}"><div class="kb-meta">${k.category}</div><h3>${k.title}</h3><p>${k.body}</p><div class="subtle">${k.views.toLocaleString()} views · Updated ${k.updated}</div><div class="kb-link">Open article →</div></article>`).join('');bindKB();}

function bindKB(){$$('.clickable-kb').forEach(card=>card.addEventListener('click',()=>openKB(card.dataset.kb)));}
function openKB(id){const k=kb.find(x=>x.id===id);if(!k)return;$('#modal-content').innerHTML=`<p class="eyebrow">KNOWLEDGE BASE · ${k.category.toUpperCase()}</p><h2 class="modal-title">${esc(k.title)}</h2><p class="modal-sub">${k.views.toLocaleString()} views · Updated ${esc(k.updated)}</p><div class="kb-article">${k.content.map(([h,b])=>`<section class="detail-section" style="margin-top:12px"><h3>${esc(h)}</h3><p style="font-size:12px;line-height:1.65;margin:0;color:#46554b">${esc(b)}</p></section>`).join('')}<div class="subtle" style="margin-top:14px;line-height:1.5"><strong>Reference note:</strong> ${esc(k.source)}</div></div>`;$('#ticket-modal').classList.add('open');$('#ticket-modal').setAttribute('aria-hidden','false');}
function renderQA(){$('#escalation-list').innerHTML=escalations.map(e=>`<div class="stack-item"><div class="stack-top"><strong>${e[0]} · ${e[1]}</strong>${tag(e[3],e[3].toLowerCase())}</div><p>${e[2]} · ${e[4]}</p></div>`).join('');$('#qa-list').innerHTML=qa.map(q=>`<div class="stack-item"><div class="stack-top"><strong>${q[0]} · ${q[1]}</strong><strong>${q[2]}</strong></div><p>${q[3]}</p></div>`).join('');}
function renderAudit(){$('#audit-list').innerHTML=audit.map(a=>`<div class="audit-item"><div class="audit-time">${a[0]}</div><div class="audit-icon">•</div><div class="audit-copy"><strong>${a[1]}</strong><span>${a[2]}</span></div><div class="subtle">${a[3]}</div></div>`).join('');}
function bindTicketRows(){$$('.clickable').forEach(row=>row.addEventListener('click',()=>openTicket(row.dataset.ticket)));}
function openTicket(id){const t=ticketData.find(x=>x.id===id);if(!t)return;$('#modal-content').innerHTML=`<p class="eyebrow">CUSTOMER TICKET</p><h2 class="modal-title">${t.id} · ${t.intent}</h2><p class="modal-sub">${t.customer} · ${t.account} · ${t.channel}</p><div style="margin-top:12px;display:flex;gap:7px;flex-wrap:wrap">${tag(t.priority,t.priority)} ${tag(t.status,t.status)} ${tag(t.risk,'escalated')}</div><div class="detail-grid"><div class="detail-section"><h3>CUSTOMER ISSUE</h3><p style="font-size:12px;line-height:1.6;margin:0;color:#46554b">${t.detail}</p><h3 style="margin-top:18px">TIMELINE</h3><div class="timeline">${t.timeline.map(x=>`<div class="timeline-item"><div class="timeline-dot"></div><div>${x}</div></div>`).join('')}</div></div><div class="detail-section"><h3>OPERATIONS</h3><p class="subtle">SLA remaining</p><strong>${t.sla}</strong><p class="subtle" style="margin-top:12px">Assigned agent</p><strong>${t.agent}</strong><p class="subtle" style="margin-top:12px">Transaction amount</p><strong>${t.amount}</strong><p class="subtle" style="margin-top:12px">Recommended action</p><strong>${t.priority==='critical'?'Escalate immediately':'Continue guided resolution'}</strong></div></div>`;$('#ticket-modal').classList.add('open');$('#ticket-modal').setAttribute('aria-hidden','false');}
function setSection(section){state.section=section;$$('.page-section').forEach(s=>s.classList.remove('active'));$('#section-'+section).classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===section));const meta={overview:['Customer Operations Overview','Monitor ticket volume, SLA exposure, customer risk, and support quality from one operating view.'],tickets:['Ticket Operations','Search, classify, assign, and resolve customer issues.'],customers:['Customer Operations','Customer context, risk signals, and support history.'],sla:['SLA Queue','Prioritize tickets by remaining response or resolution window.'],knowledge:['Knowledge Base','Operational guidance agents can use during support.'],qa:['QA & Escalations','Review customer interactions and route higher-risk cases.'],audit:['Audit Log','Chronological record of operational actions and routing events.']};$('#page-title').textContent=meta[section][0];$('#page-description').textContent=meta[section][1];if(section==='tickets')renderTickets();if(section==='customers')renderCustomers();if(section==='sla')renderSLA();if(section==='knowledge')renderKB();}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>setSection(b.dataset.section)));$$('[data-go="tickets"]').forEach(b=>b.addEventListener('click',()=>setSection('tickets')));
$('#ticket-status').addEventListener('change',e=>{state.ticketFilter.status=e.target.value;renderTickets()});$('#ticket-priority').addEventListener('change',e=>{state.ticketFilter.priority=e.target.value;renderTickets()});$('#customer-search').addEventListener('input',e=>{state.customerSearch=e.target.value;renderCustomers()});$('#kb-search').addEventListener('input',e=>{state.kbSearch=e.target.value;renderKB()});$('#global-search').addEventListener('input',()=>{if(state.section!=='tickets')setSection('tickets');else renderTickets()});$('#refresh-btn').addEventListener('click',()=>{const b=$('#refresh-btn');const old=b.textContent;b.textContent='Refreshing…';setTimeout(()=>b.textContent=old,700);renderOverview();if(state.section==='tickets')renderTickets();});$('#modal-close').addEventListener('click',()=>{ $('#ticket-modal').classList.remove('open'); $('#ticket-modal').setAttribute('aria-hidden','true'); });$('#ticket-modal').addEventListener('click',e=>{if(e.target.id==='ticket-modal'){ $('#ticket-modal').classList.remove('open'); $('#ticket-modal').setAttribute('aria-hidden','true'); }});
renderOverview();renderCustomers();renderKB();renderQA();renderAudit();
